/*

 GAME_MAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\vince\Documents\gameboydev\bug\bug_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_mapWidth 20
#define game_mapHeight 18
#define game_mapBank 0

unsigned const char window_map[] =
{
  0x0B,0x0A,0x0A,0x0A,0x0A,0x0A,0x0A,0x0A,0x0A,0x0B
};

/* End of GAME_MAP.C */
